/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_window = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_stream = 6,
  anon_sym_EQ = 7,
  anon_sym_LBRACK = 8,
  anon_sym_COMMA = 9,
  anon_sym_RBRACK = 10,
  anon_sym_time = 11,
  anon_sym_over = 12,
  anon_sym_0 = 13,
  anon_sym_fields = 14,
  anon_sym_COLON = 15,
  anon_sym_DOT = 16,
  sym_quoted_identifier = 17,
  anon_sym_array = 18,
  anon_sym_SLASH = 19,
  sym_object_type = 20,
  anon_sym_chars = 21,
  anon_sym_digit = 22,
  anon_sym_float = 23,
  anon_sym_bool = 24,
  anon_sym_ip = 25,
  anon_sym_hex = 26,
  sym_duration = 27,
  sym_string = 28,
  sym_source_file = 29,
  sym_window_declaration = 30,
  sym_window_attribute = 31,
  sym_stream_attribute = 32,
  sym_string_array = 33,
  sym_time_attribute = 34,
  sym_over_attribute = 35,
  sym_fields_block = 36,
  sym_field_declaration = 37,
  sym_field_name = 38,
  sym_dotted_identifier = 39,
  sym_field_type = 40,
  sym_array_type = 41,
  sym_base_type = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_window_declaration_repeat1 = 44,
  aux_sym_string_array_repeat1 = 45,
  aux_sym_fields_block_repeat1 = 46,
  aux_sym_dotted_identifier_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_window] = "window",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_stream] = "stream",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_time] = "time",
  [anon_sym_over] = "over",
  [anon_sym_0] = "0",
  [anon_sym_fields] = "fields",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [sym_quoted_identifier] = "quoted_identifier",
  [anon_sym_array] = "array",
  [anon_sym_SLASH] = "/",
  [sym_object_type] = "object_type",
  [anon_sym_chars] = "chars",
  [anon_sym_digit] = "digit",
  [anon_sym_float] = "float",
  [anon_sym_bool] = "bool",
  [anon_sym_ip] = "ip",
  [anon_sym_hex] = "hex",
  [sym_duration] = "duration",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_window_declaration] = "window_declaration",
  [sym_window_attribute] = "window_attribute",
  [sym_stream_attribute] = "stream_attribute",
  [sym_string_array] = "string_array",
  [sym_time_attribute] = "time_attribute",
  [sym_over_attribute] = "over_attribute",
  [sym_fields_block] = "fields_block",
  [sym_field_declaration] = "field_declaration",
  [sym_field_name] = "field_name",
  [sym_dotted_identifier] = "dotted_identifier",
  [sym_field_type] = "field_type",
  [sym_array_type] = "array_type",
  [sym_base_type] = "base_type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_window_declaration_repeat1] = "window_declaration_repeat1",
  [aux_sym_string_array_repeat1] = "string_array_repeat1",
  [aux_sym_fields_block_repeat1] = "fields_block_repeat1",
  [aux_sym_dotted_identifier_repeat1] = "dotted_identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_window] = anon_sym_window,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_stream] = anon_sym_stream,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_time] = anon_sym_time,
  [anon_sym_over] = anon_sym_over,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_fields] = anon_sym_fields,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_quoted_identifier] = sym_quoted_identifier,
  [anon_sym_array] = anon_sym_array,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_object_type] = sym_object_type,
  [anon_sym_chars] = anon_sym_chars,
  [anon_sym_digit] = anon_sym_digit,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_ip] = anon_sym_ip,
  [anon_sym_hex] = anon_sym_hex,
  [sym_duration] = sym_duration,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_window_declaration] = sym_window_declaration,
  [sym_window_attribute] = sym_window_attribute,
  [sym_stream_attribute] = sym_stream_attribute,
  [sym_string_array] = sym_string_array,
  [sym_time_attribute] = sym_time_attribute,
  [sym_over_attribute] = sym_over_attribute,
  [sym_fields_block] = sym_fields_block,
  [sym_field_declaration] = sym_field_declaration,
  [sym_field_name] = sym_field_name,
  [sym_dotted_identifier] = sym_dotted_identifier,
  [sym_field_type] = sym_field_type,
  [sym_array_type] = sym_array_type,
  [sym_base_type] = sym_base_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_window_declaration_repeat1] = aux_sym_window_declaration_repeat1,
  [aux_sym_string_array_repeat1] = aux_sym_string_array_repeat1,
  [aux_sym_fields_block_repeat1] = aux_sym_fields_block_repeat1,
  [aux_sym_dotted_identifier_repeat1] = aux_sym_dotted_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_window] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stream] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_time] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_over] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fields] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_array] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_object_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_chars] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_digit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hex] = {
    .visible = true,
    .named = false,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_window_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_window_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_stream_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_string_array] = {
    .visible = true,
    .named = true,
  },
  [sym_time_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_over_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_fields_block] = {
    .visible = true,
    .named = true,
  },
  [sym_field_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_field_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_base_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_window_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fields_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_type = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
    {field_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 1,
        ',', 12,
        '.', 16,
        '/', 18,
        '0', 14,
        ':', 15,
        '=', 10,
        '[', 11,
        ']', 13,
        '`', 5,
        '{', 8,
        '}', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '`') ADVANCE(17);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(2);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_0);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_quoted_identifier);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(7);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_duration);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'f', 5,
        'h', 6,
        'i', 7,
        'o', 8,
        's', 9,
        't', 10,
        'w', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'h') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(16);
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(20);
      if (lookahead == 'v') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 18:
      if (lookahead == 'x') ADVANCE(31);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_ip);
      END_STATE();
    case 20:
      if (lookahead == 'j') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_hex);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 36:
      if (lookahead == 'd') ADVANCE(47);
      END_STATE();
    case 37:
      if (lookahead == 'y') ADVANCE(48);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(49);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 41:
      if (lookahead == 'd') ADVANCE(51);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 43:
      if (lookahead == 'c') ADVANCE(53);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_over);
      END_STATE();
    case 45:
      if (lookahead == 'a') ADVANCE(54);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_time);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(55);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_array);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_chars);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_digit);
      END_STATE();
    case 51:
      if (lookahead == 's') ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == 'm') ADVANCE(58);
      END_STATE();
    case 55:
      if (lookahead == 'w') ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_fields);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_object_type);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_stream);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_window);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_window] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_stream] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_time] = ACTIONS(1),
    [anon_sym_over] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_fields] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_quoted_identifier] = ACTIONS(1),
    [anon_sym_array] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_object_type] = ACTIONS(1),
    [anon_sym_chars] = ACTIONS(1),
    [anon_sym_digit] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_ip] = ACTIONS(1),
    [anon_sym_hex] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(53),
    [sym_window_declaration] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_window] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_array,
    ACTIONS(13), 1,
      sym_object_type,
    STATE(24), 1,
      sym_field_type,
    STATE(23), 2,
      sym_array_type,
      sym_base_type,
    ACTIONS(9), 7,
      anon_sym_time,
      anon_sym_chars,
      anon_sym_digit,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_ip,
      anon_sym_hex,
  [26] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_stream,
    ACTIONS(17), 1,
      anon_sym_time,
    ACTIONS(19), 1,
      anon_sym_over,
    ACTIONS(21), 1,
      anon_sym_fields,
    STATE(42), 1,
      sym_fields_block,
    STATE(5), 2,
      sym_window_attribute,
      aux_sym_window_declaration_repeat1,
    STATE(11), 3,
      sym_stream_attribute,
      sym_time_attribute,
      sym_over_attribute,
  [54] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_stream,
    ACTIONS(17), 1,
      anon_sym_time,
    ACTIONS(19), 1,
      anon_sym_over,
    ACTIONS(21), 1,
      anon_sym_fields,
    STATE(45), 1,
      sym_fields_block,
    STATE(3), 2,
      sym_window_attribute,
      aux_sym_window_declaration_repeat1,
    STATE(11), 3,
      sym_stream_attribute,
      sym_time_attribute,
      sym_over_attribute,
  [82] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_stream,
    ACTIONS(26), 1,
      anon_sym_time,
    ACTIONS(29), 1,
      anon_sym_over,
    ACTIONS(32), 1,
      anon_sym_fields,
    STATE(5), 2,
      sym_window_attribute,
      aux_sym_window_declaration_repeat1,
    STATE(11), 3,
      sym_stream_attribute,
      sym_time_attribute,
      sym_over_attribute,
  [107] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(29), 1,
      sym_base_type,
    ACTIONS(9), 7,
      anon_sym_time,
      anon_sym_chars,
      anon_sym_digit,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_ip,
      anon_sym_hex,
  [123] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      sym_identifier,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    ACTIONS(38), 1,
      sym_quoted_identifier,
    STATE(48), 1,
      sym_dotted_identifier,
    STATE(52), 1,
      sym_field_name,
    STATE(8), 2,
      sym_field_declaration,
      aux_sym_fields_block_repeat1,
  [146] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      sym_quoted_identifier,
    STATE(48), 1,
      sym_dotted_identifier,
    STATE(52), 1,
      sym_field_name,
    STATE(8), 2,
      sym_field_declaration,
      aux_sym_fields_block_repeat1,
  [169] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      sym_identifier,
    ACTIONS(38), 1,
      sym_quoted_identifier,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      sym_dotted_identifier,
    STATE(52), 1,
      sym_field_name,
    STATE(7), 2,
      sym_field_declaration,
      aux_sym_fields_block_repeat1,
  [192] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_SLASH,
    ACTIONS(50), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [204] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 4,
      anon_sym_stream,
      anon_sym_time,
      anon_sym_over,
      anon_sym_fields,
  [214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 4,
      anon_sym_stream,
      anon_sym_time,
      anon_sym_over,
      anon_sym_fields,
  [224] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_window,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    STATE(14), 2,
      sym_window_declaration,
      aux_sym_source_file_repeat1,
  [238] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      anon_sym_window,
    STATE(14), 2,
      sym_window_declaration,
      aux_sym_source_file_repeat1,
  [252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 4,
      anon_sym_stream,
      anon_sym_time,
      anon_sym_over,
      anon_sym_fields,
  [262] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 4,
      anon_sym_stream,
      anon_sym_time,
      anon_sym_over,
      anon_sym_fields,
  [272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 4,
      anon_sym_stream,
      anon_sym_time,
      anon_sym_over,
      anon_sym_fields,
  [282] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 4,
      anon_sym_stream,
      anon_sym_time,
      anon_sym_over,
      anon_sym_fields,
  [292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      sym_string,
    STATE(12), 1,
      sym_string_array,
  [305] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    ACTIONS(79), 1,
      anon_sym_RBRACK,
    STATE(22), 1,
      aux_sym_string_array_repeat1,
  [318] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_COLON,
    ACTIONS(83), 1,
      anon_sym_DOT,
    STATE(27), 1,
      aux_sym_dotted_identifier_repeat1,
  [331] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    ACTIONS(85), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      aux_sym_string_array_repeat1,
  [344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [353] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [362] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [371] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_COMMA,
    ACTIONS(96), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      aux_sym_string_array_repeat1,
  [384] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_DOT,
    ACTIONS(98), 1,
      anon_sym_COLON,
    STATE(28), 1,
      aux_sym_dotted_identifier_repeat1,
  [397] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_COLON,
    ACTIONS(102), 1,
      anon_sym_DOT,
    STATE(28), 1,
      aux_sym_dotted_identifier_repeat1,
  [410] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 3,
      anon_sym_RBRACE,
      sym_quoted_identifier,
      sym_identifier,
  [419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      anon_sym_window,
  [427] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      anon_sym_window,
  [435] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [443] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_COLON,
    ACTIONS(113), 1,
      anon_sym_DOT,
  [453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_0,
    ACTIONS(117), 1,
      sym_duration,
  [463] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 2,
      anon_sym_COLON,
      anon_sym_DOT,
  [471] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
  [478] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      sym_identifier,
  [485] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_identifier,
  [492] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
  [499] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_EQ,
  [506] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_string,
  [513] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
  [520] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_LBRACE,
  [527] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_string,
  [534] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
  [541] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_EQ,
  [548] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
  [555] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_COLON,
  [562] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identifier,
  [569] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_identifier,
  [576] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_EQ,
  [583] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_COLON,
  [590] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 82,
  [SMALL_STATE(6)] = 107,
  [SMALL_STATE(7)] = 123,
  [SMALL_STATE(8)] = 146,
  [SMALL_STATE(9)] = 169,
  [SMALL_STATE(10)] = 192,
  [SMALL_STATE(11)] = 204,
  [SMALL_STATE(12)] = 214,
  [SMALL_STATE(13)] = 224,
  [SMALL_STATE(14)] = 238,
  [SMALL_STATE(15)] = 252,
  [SMALL_STATE(16)] = 262,
  [SMALL_STATE(17)] = 272,
  [SMALL_STATE(18)] = 282,
  [SMALL_STATE(19)] = 292,
  [SMALL_STATE(20)] = 305,
  [SMALL_STATE(21)] = 318,
  [SMALL_STATE(22)] = 331,
  [SMALL_STATE(23)] = 344,
  [SMALL_STATE(24)] = 353,
  [SMALL_STATE(25)] = 362,
  [SMALL_STATE(26)] = 371,
  [SMALL_STATE(27)] = 384,
  [SMALL_STATE(28)] = 397,
  [SMALL_STATE(29)] = 410,
  [SMALL_STATE(30)] = 419,
  [SMALL_STATE(31)] = 427,
  [SMALL_STATE(32)] = 435,
  [SMALL_STATE(33)] = 443,
  [SMALL_STATE(34)] = 453,
  [SMALL_STATE(35)] = 463,
  [SMALL_STATE(36)] = 471,
  [SMALL_STATE(37)] = 478,
  [SMALL_STATE(38)] = 485,
  [SMALL_STATE(39)] = 492,
  [SMALL_STATE(40)] = 499,
  [SMALL_STATE(41)] = 506,
  [SMALL_STATE(42)] = 513,
  [SMALL_STATE(43)] = 520,
  [SMALL_STATE(44)] = 527,
  [SMALL_STATE(45)] = 534,
  [SMALL_STATE(46)] = 541,
  [SMALL_STATE(47)] = 548,
  [SMALL_STATE(48)] = 555,
  [SMALL_STATE(49)] = 562,
  [SMALL_STATE(50)] = 569,
  [SMALL_STATE(51)] = 576,
  [SMALL_STATE(52)] = 583,
  [SMALL_STATE(53)] = 590,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_window_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_window_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_window_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_window_declaration_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fields_block_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fields_block_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fields_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_window_attribute, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stream_attribute, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_attribute, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_over_attribute, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_array, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_array, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_identifier, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_type, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 3, 0, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_base_type, 1, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_array_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_array_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_identifier, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_window_declaration, 6, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_window_declaration, 5, 0, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields_block, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields_block, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [151] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wfs(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "wfs",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
