/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 161
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 82
#define ALIAS_COUNT 0
#define TOKEN_COUNT 47
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 26
#define MAX_ALIAS_SEQUENCE_LENGTH 18
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_use = 3,
  anon_sym_POUND_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_scenario = 6,
  anon_sym_LT = 7,
  anon_sym_GT = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_COMMA = 11,
  anon_sym_EQ = 12,
  anon_sym_traffic = 13,
  anon_sym_stream = 14,
  anon_sym_gen = 15,
  sym_rate_constant = 16,
  anon_sym_wave = 17,
  anon_sym_LPAREN = 18,
  anon_sym_base = 19,
  anon_sym_amp = 20,
  anon_sym_period = 21,
  anon_sym_shape = 22,
  anon_sym_RPAREN = 23,
  anon_sym_sine = 24,
  anon_sym_triangle = 25,
  anon_sym_square = 26,
  anon_sym_burst = 27,
  anon_sym_peak = 28,
  anon_sym_every = 29,
  anon_sym_hold = 30,
  anon_sym_timeline = 31,
  anon_sym_DOT_DOT = 32,
  anon_sym_injection = 33,
  anon_sym_hit = 34,
  anon_sym_near_miss = 35,
  anon_sym_miss = 36,
  anon_sym_seq = 37,
  anon_sym_with = 38,
  anon_sym_expect = 39,
  sym_comparison_operator = 40,
  sym_percent = 41,
  sym_duration = 42,
  sym_number = 43,
  sym_string = 44,
  anon_sym_true = 45,
  anon_sym_false = 46,
  sym_source_file = 47,
  sym_use_declaration = 48,
  sym_scenario_attributes = 49,
  sym_scenario_declaration = 50,
  sym_annotation_list = 51,
  sym_annotation_item = 52,
  sym_traffic_block = 53,
  sym_stream_statement = 54,
  sym_rate_expression = 55,
  sym_wave_expression = 56,
  sym_wave_shape = 57,
  sym_burst_expression = 58,
  sym_timeline_expression = 59,
  sym_timeline_segment = 60,
  sym_injection_block = 61,
  sym_injection_case = 62,
  sym_mode_keyword = 63,
  sym_sequence_block = 64,
  sym_use_statement = 65,
  sym_predicate_list = 66,
  sym_predicate = 67,
  sym_expect_block = 68,
  sym_expect_statement = 69,
  sym_expect_function = 70,
  sym_value = 71,
  sym_literal = 72,
  sym_boolean = 73,
  aux_sym_source_file_repeat1 = 74,
  aux_sym_annotation_list_repeat1 = 75,
  aux_sym_traffic_block_repeat1 = 76,
  aux_sym_timeline_expression_repeat1 = 77,
  aux_sym_injection_block_repeat1 = 78,
  aux_sym_sequence_block_repeat1 = 79,
  aux_sym_predicate_list_repeat1 = 80,
  aux_sym_expect_block_repeat1 = 81,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_use] = "use",
  [anon_sym_POUND_LBRACK] = "#[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_scenario] = "scenario",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_traffic] = "traffic",
  [anon_sym_stream] = "stream",
  [anon_sym_gen] = "gen",
  [sym_rate_constant] = "rate_constant",
  [anon_sym_wave] = "wave",
  [anon_sym_LPAREN] = "(",
  [anon_sym_base] = "base",
  [anon_sym_amp] = "amp",
  [anon_sym_period] = "period",
  [anon_sym_shape] = "shape",
  [anon_sym_RPAREN] = ")",
  [anon_sym_sine] = "sine",
  [anon_sym_triangle] = "triangle",
  [anon_sym_square] = "square",
  [anon_sym_burst] = "burst",
  [anon_sym_peak] = "peak",
  [anon_sym_every] = "every",
  [anon_sym_hold] = "hold",
  [anon_sym_timeline] = "timeline",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_injection] = "injection",
  [anon_sym_hit] = "hit",
  [anon_sym_near_miss] = "near_miss",
  [anon_sym_miss] = "miss",
  [anon_sym_seq] = "seq",
  [anon_sym_with] = "with",
  [anon_sym_expect] = "expect",
  [sym_comparison_operator] = "comparison_operator",
  [sym_percent] = "percent",
  [sym_duration] = "duration",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_use_declaration] = "use_declaration",
  [sym_scenario_attributes] = "scenario_attributes",
  [sym_scenario_declaration] = "scenario_declaration",
  [sym_annotation_list] = "annotation_list",
  [sym_annotation_item] = "annotation_item",
  [sym_traffic_block] = "traffic_block",
  [sym_stream_statement] = "stream_statement",
  [sym_rate_expression] = "rate_expression",
  [sym_wave_expression] = "wave_expression",
  [sym_wave_shape] = "wave_shape",
  [sym_burst_expression] = "burst_expression",
  [sym_timeline_expression] = "timeline_expression",
  [sym_timeline_segment] = "timeline_segment",
  [sym_injection_block] = "injection_block",
  [sym_injection_case] = "injection_case",
  [sym_mode_keyword] = "mode_keyword",
  [sym_sequence_block] = "sequence_block",
  [sym_use_statement] = "use_statement",
  [sym_predicate_list] = "predicate_list",
  [sym_predicate] = "predicate",
  [sym_expect_block] = "expect_block",
  [sym_expect_statement] = "expect_statement",
  [sym_expect_function] = "expect_function",
  [sym_value] = "value",
  [sym_literal] = "literal",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_annotation_list_repeat1] = "annotation_list_repeat1",
  [aux_sym_traffic_block_repeat1] = "traffic_block_repeat1",
  [aux_sym_timeline_expression_repeat1] = "timeline_expression_repeat1",
  [aux_sym_injection_block_repeat1] = "injection_block_repeat1",
  [aux_sym_sequence_block_repeat1] = "sequence_block_repeat1",
  [aux_sym_predicate_list_repeat1] = "predicate_list_repeat1",
  [aux_sym_expect_block_repeat1] = "expect_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_POUND_LBRACK] = anon_sym_POUND_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_scenario] = anon_sym_scenario,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_traffic] = anon_sym_traffic,
  [anon_sym_stream] = anon_sym_stream,
  [anon_sym_gen] = anon_sym_gen,
  [sym_rate_constant] = sym_rate_constant,
  [anon_sym_wave] = anon_sym_wave,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_base] = anon_sym_base,
  [anon_sym_amp] = anon_sym_amp,
  [anon_sym_period] = anon_sym_period,
  [anon_sym_shape] = anon_sym_shape,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_sine] = anon_sym_sine,
  [anon_sym_triangle] = anon_sym_triangle,
  [anon_sym_square] = anon_sym_square,
  [anon_sym_burst] = anon_sym_burst,
  [anon_sym_peak] = anon_sym_peak,
  [anon_sym_every] = anon_sym_every,
  [anon_sym_hold] = anon_sym_hold,
  [anon_sym_timeline] = anon_sym_timeline,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_injection] = anon_sym_injection,
  [anon_sym_hit] = anon_sym_hit,
  [anon_sym_near_miss] = anon_sym_near_miss,
  [anon_sym_miss] = anon_sym_miss,
  [anon_sym_seq] = anon_sym_seq,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_expect] = anon_sym_expect,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_percent] = sym_percent,
  [sym_duration] = sym_duration,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_use_declaration] = sym_use_declaration,
  [sym_scenario_attributes] = sym_scenario_attributes,
  [sym_scenario_declaration] = sym_scenario_declaration,
  [sym_annotation_list] = sym_annotation_list,
  [sym_annotation_item] = sym_annotation_item,
  [sym_traffic_block] = sym_traffic_block,
  [sym_stream_statement] = sym_stream_statement,
  [sym_rate_expression] = sym_rate_expression,
  [sym_wave_expression] = sym_wave_expression,
  [sym_wave_shape] = sym_wave_shape,
  [sym_burst_expression] = sym_burst_expression,
  [sym_timeline_expression] = sym_timeline_expression,
  [sym_timeline_segment] = sym_timeline_segment,
  [sym_injection_block] = sym_injection_block,
  [sym_injection_case] = sym_injection_case,
  [sym_mode_keyword] = sym_mode_keyword,
  [sym_sequence_block] = sym_sequence_block,
  [sym_use_statement] = sym_use_statement,
  [sym_predicate_list] = sym_predicate_list,
  [sym_predicate] = sym_predicate,
  [sym_expect_block] = sym_expect_block,
  [sym_expect_statement] = sym_expect_statement,
  [sym_expect_function] = sym_expect_function,
  [sym_value] = sym_value,
  [sym_literal] = sym_literal,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_annotation_list_repeat1] = aux_sym_annotation_list_repeat1,
  [aux_sym_traffic_block_repeat1] = aux_sym_traffic_block_repeat1,
  [aux_sym_timeline_expression_repeat1] = aux_sym_timeline_expression_repeat1,
  [aux_sym_injection_block_repeat1] = aux_sym_injection_block_repeat1,
  [aux_sym_sequence_block_repeat1] = aux_sym_sequence_block_repeat1,
  [aux_sym_predicate_list_repeat1] = aux_sym_predicate_list_repeat1,
  [aux_sym_expect_block_repeat1] = aux_sym_expect_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scenario] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_traffic] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stream] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gen] = {
    .visible = true,
    .named = false,
  },
  [sym_rate_constant] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_wave] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_base] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_amp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_period] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_shape] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sine] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_triangle] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_square] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_burst] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_peak] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_every] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hold] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_timeline] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_injection] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_near_miss] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_miss] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_seq] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_expect] = {
    .visible = true,
    .named = false,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_percent] = {
    .visible = true,
    .named = true,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_use_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation_list] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation_item] = {
    .visible = true,
    .named = true,
  },
  [sym_traffic_block] = {
    .visible = true,
    .named = true,
  },
  [sym_stream_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_rate_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_wave_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_wave_shape] = {
    .visible = true,
    .named = true,
  },
  [sym_burst_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_timeline_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_timeline_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_injection_block] = {
    .visible = true,
    .named = true,
  },
  [sym_injection_case] = {
    .visible = true,
    .named = true,
  },
  [sym_mode_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence_block] = {
    .visible = true,
    .named = true,
  },
  [sym_use_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate_list] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate] = {
    .visible = true,
    .named = true,
  },
  [sym_expect_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expect_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expect_function] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_annotation_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_traffic_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_timeline_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_injection_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_predicate_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expect_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_amp = 1,
  field_base = 2,
  field_count = 3,
  field_end = 4,
  field_entity = 5,
  field_every = 6,
  field_hold = 7,
  field_key = 8,
  field_metric = 9,
  field_mode = 10,
  field_name = 11,
  field_operator = 12,
  field_params = 13,
  field_path = 14,
  field_peak = 15,
  field_percent = 16,
  field_period = 17,
  field_predicates = 18,
  field_rate = 19,
  field_rule = 20,
  field_shape = 21,
  field_start = 22,
  field_stream = 23,
  field_threshold = 24,
  field_value = 25,
  field_window = 26,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_amp] = "amp",
  [field_base] = "base",
  [field_count] = "count",
  [field_end] = "end",
  [field_entity] = "entity",
  [field_every] = "every",
  [field_hold] = "hold",
  [field_key] = "key",
  [field_metric] = "metric",
  [field_mode] = "mode",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_params] = "params",
  [field_path] = "path",
  [field_peak] = "peak",
  [field_percent] = "percent",
  [field_period] = "period",
  [field_predicates] = "predicates",
  [field_rate] = "rate",
  [field_rule] = "rule",
  [field_shape] = "shape",
  [field_start] = "start",
  [field_stream] = "stream",
  [field_threshold] = "threshold",
  [field_value] = "value",
  [field_window] = "window",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 4},
  [7] = {.index = 12, .length = 3},
  [8] = {.index = 15, .length = 3},
  [9] = {.index = 18, .length = 1},
  [10] = {.index = 19, .length = 3},
  [11] = {.index = 22, .length = 3},
  [12] = {.index = 25, .length = 4},
  [13] = {.index = 29, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_key, 0},
    {field_value, 2},
  [3] =
    {field_name, 1},
  [4] =
    {field_name, 1},
    {field_params, 3},
  [6] =
    {field_rate, 3},
    {field_stream, 1},
  [8] =
    {field_metric, 0},
    {field_operator, 4},
    {field_rule, 2},
    {field_threshold, 5},
  [12] =
    {field_mode, 0},
    {field_percent, 2},
    {field_stream, 4},
  [15] =
    {field_end, 2},
    {field_rate, 4},
    {field_start, 0},
  [18] =
    {field_entity, 0},
  [19] =
    {field_amp, 8},
    {field_base, 4},
    {field_period, 12},
  [22] =
    {field_count, 6},
    {field_predicates, 2},
    {field_window, 8},
  [25] =
    {field_amp, 8},
    {field_base, 4},
    {field_period, 12},
    {field_shape, 16},
  [29] =
    {field_base, 4},
    {field_every, 12},
    {field_hold, 16},
    {field_peak, 8},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 149,
  [150] = 150,
  [151] = 151,
  [152] = 152,
  [153] = 153,
  [154] = 154,
  [155] = 155,
  [156] = 156,
  [157] = 157,
  [158] = 158,
  [159] = 159,
  [160] = 160,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 2,
        '#', 9,
        '(', 29,
        ')', 30,
        ',', 25,
        '.', 5,
        '/', 7,
        '<', 20,
        '=', 27,
        '>', 22,
        ']', 18,
        '{', 23,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        ')', 30,
        ',', 25,
        '/', 7,
        '<', 19,
        '=', 26,
        '>', 21,
        ']', 18,
        '{', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(34);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == '/') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(34);
      if (lookahead == '/') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(31);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(33);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '>') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 9:
      if (lookahead == '[') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_rate_constant);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comparison_operator);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comparison_operator);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_percent);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_duration);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(34);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'e', 3,
        'f', 4,
        'g', 5,
        'h', 6,
        'i', 7,
        'm', 8,
        'n', 9,
        'p', 10,
        's', 11,
        't', 12,
        'u', 13,
        'w', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'v') ADVANCE(18);
      if (lookahead == 'x') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(28);
      if (lookahead == 'e') ADVANCE(29);
      if (lookahead == 'h') ADVANCE(30);
      if (lookahead == 'i') ADVANCE(31);
      if (lookahead == 'q') ADVANCE(32);
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(34);
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(36);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(37);
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 'p') ADVANCE(39);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(43);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 24:
      if (lookahead == 'j') ADVANCE(48);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(49);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(50);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(51);
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 29:
      if (lookahead == 'q') ADVANCE(54);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(55);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 34:
      if (lookahead == 'm') ADVANCE(59);
      END_STATE();
    case 35:
      if (lookahead == 'a') ADVANCE(60);
      if (lookahead == 'i') ADVANCE(61);
      if (lookahead == 'u') ADVANCE(62);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 37:
      if (lookahead == 'v') ADVANCE(64);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_amp);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(67);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(68);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(70);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_gen);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_hit);
      END_STATE();
    case 47:
      if (lookahead == 'd') ADVANCE(71);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(74);
      END_STATE();
    case 51:
      if (lookahead == 'k') ADVANCE(75);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(76);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_seq);
      END_STATE();
    case 55:
      if (lookahead == 'p') ADVANCE(78);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 57:
      if (lookahead == 'a') ADVANCE(80);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 60:
      if (lookahead == 'f') ADVANCE(83);
      END_STATE();
    case 61:
      if (lookahead == 'a') ADVANCE(84);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 65:
      if (lookahead == 'h') ADVANCE(87);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_base);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(88);
      END_STATE();
    case 68:
      if (lookahead == 'y') ADVANCE(89);
      END_STATE();
    case 69:
      if (lookahead == 'c') ADVANCE(90);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_hold);
      END_STATE();
    case 72:
      if (lookahead == 'c') ADVANCE(92);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_miss);
      END_STATE();
    case 74:
      if (lookahead == '_') ADVANCE(93);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_peak);
      END_STATE();
    case 76:
      if (lookahead == 'o') ADVANCE(94);
      END_STATE();
    case 77:
      if (lookahead == 'a') ADVANCE(95);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(96);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_sine);
      END_STATE();
    case 80:
      if (lookahead == 'r') ADVANCE(97);
      END_STATE();
    case 81:
      if (lookahead == 'a') ADVANCE(98);
      END_STATE();
    case 82:
      if (lookahead == 'l') ADVANCE(99);
      END_STATE();
    case 83:
      if (lookahead == 'f') ADVANCE(100);
      END_STATE();
    case 84:
      if (lookahead == 'n') ADVANCE(101);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_wave);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_burst);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_every);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(102);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 92:
      if (lookahead == 't') ADVANCE(103);
      END_STATE();
    case 93:
      if (lookahead == 'm') ADVANCE(104);
      END_STATE();
    case 94:
      if (lookahead == 'd') ADVANCE(105);
      END_STATE();
    case 95:
      if (lookahead == 'r') ADVANCE(106);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_shape);
      END_STATE();
    case 97:
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 98:
      if (lookahead == 'm') ADVANCE(108);
      END_STATE();
    case 99:
      if (lookahead == 'i') ADVANCE(109);
      END_STATE();
    case 100:
      if (lookahead == 'i') ADVANCE(110);
      END_STATE();
    case 101:
      if (lookahead == 'g') ADVANCE(111);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_expect);
      END_STATE();
    case 103:
      if (lookahead == 'i') ADVANCE(112);
      END_STATE();
    case 104:
      if (lookahead == 'i') ADVANCE(113);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_period);
      END_STATE();
    case 106:
      if (lookahead == 'i') ADVANCE(114);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_square);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_stream);
      END_STATE();
    case 109:
      if (lookahead == 'n') ADVANCE(115);
      END_STATE();
    case 110:
      if (lookahead == 'c') ADVANCE(116);
      END_STATE();
    case 111:
      if (lookahead == 'l') ADVANCE(117);
      END_STATE();
    case 112:
      if (lookahead == 'o') ADVANCE(118);
      END_STATE();
    case 113:
      if (lookahead == 's') ADVANCE(119);
      END_STATE();
    case 114:
      if (lookahead == 'o') ADVANCE(120);
      END_STATE();
    case 115:
      if (lookahead == 'e') ADVANCE(121);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_traffic);
      END_STATE();
    case 117:
      if (lookahead == 'e') ADVANCE(122);
      END_STATE();
    case 118:
      if (lookahead == 'n') ADVANCE(123);
      END_STATE();
    case 119:
      if (lookahead == 's') ADVANCE(124);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_scenario);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_timeline);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_triangle);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_injection);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_near_miss);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 6},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 6},
  [92] = {.lex_state = 6},
  [93] = {.lex_state = 6},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 6},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 1},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 6},
  [114] = {.lex_state = 6},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 1},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 1},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 1},
  [130] = {.lex_state = 1},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 1},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 1},
  [149] = {.lex_state = 1},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 6},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 0},
  [160] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_POUND_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_scenario] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_traffic] = ACTIONS(1),
    [anon_sym_stream] = ACTIONS(1),
    [anon_sym_gen] = ACTIONS(1),
    [anon_sym_wave] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_base] = ACTIONS(1),
    [anon_sym_amp] = ACTIONS(1),
    [anon_sym_period] = ACTIONS(1),
    [anon_sym_shape] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_sine] = ACTIONS(1),
    [anon_sym_triangle] = ACTIONS(1),
    [anon_sym_square] = ACTIONS(1),
    [anon_sym_burst] = ACTIONS(1),
    [anon_sym_peak] = ACTIONS(1),
    [anon_sym_every] = ACTIONS(1),
    [anon_sym_hold] = ACTIONS(1),
    [anon_sym_timeline] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_injection] = ACTIONS(1),
    [anon_sym_hit] = ACTIONS(1),
    [anon_sym_near_miss] = ACTIONS(1),
    [anon_sym_miss] = ACTIONS(1),
    [anon_sym_seq] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_expect] = ACTIONS(1),
    [sym_comparison_operator] = ACTIONS(1),
    [sym_percent] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(76),
    [sym_use_declaration] = STATE(4),
    [sym_scenario_attributes] = STATE(48),
    [sym_scenario_declaration] = STATE(116),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(5),
    [anon_sym_POUND_LBRACK] = ACTIONS(7),
    [anon_sym_scenario] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_duration,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      sym_string,
    STATE(21), 1,
      sym_boolean,
    STATE(34), 1,
      sym_literal,
    STATE(38), 1,
      sym_value,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [26] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym_rate_constant,
    ACTIONS(21), 1,
      anon_sym_wave,
    ACTIONS(23), 1,
      anon_sym_burst,
    ACTIONS(25), 1,
      anon_sym_timeline,
    STATE(55), 1,
      sym_rate_expression,
    STATE(54), 3,
      sym_wave_expression,
      sym_burst_expression,
      sym_timeline_expression,
  [50] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      anon_sym_use,
    ACTIONS(7), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(9), 1,
      anon_sym_scenario,
    STATE(47), 1,
      sym_scenario_attributes,
    STATE(134), 1,
      sym_scenario_declaration,
    STATE(14), 2,
      sym_use_declaration,
      aux_sym_source_file_repeat1,
  [73] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(121), 1,
      sym_mode_keyword,
    STATE(6), 2,
      sym_injection_case,
      aux_sym_injection_block_repeat1,
    ACTIONS(29), 3,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_miss,
  [92] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(121), 1,
      sym_mode_keyword,
    STATE(6), 2,
      sym_injection_case,
      aux_sym_injection_block_repeat1,
    ACTIONS(33), 3,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_miss,
  [111] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    STATE(133), 1,
      sym_expect_function,
    STATE(8), 2,
      sym_expect_statement,
      aux_sym_expect_block_repeat1,
    ACTIONS(38), 3,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_miss,
  [130] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    STATE(133), 1,
      sym_expect_function,
    STATE(10), 2,
      sym_expect_statement,
      aux_sym_expect_block_repeat1,
    ACTIONS(38), 3,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_miss,
  [149] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    STATE(121), 1,
      sym_mode_keyword,
    STATE(5), 2,
      sym_injection_case,
      aux_sym_injection_block_repeat1,
    ACTIONS(29), 3,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_miss,
  [168] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    STATE(133), 1,
      sym_expect_function,
    STATE(10), 2,
      sym_expect_statement,
      aux_sym_expect_block_repeat1,
    ACTIONS(46), 3,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_miss,
  [187] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(21), 1,
      sym_boolean,
    STATE(59), 1,
      sym_literal,
    ACTIONS(15), 2,
      sym_number,
      sym_string,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
  [205] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      anon_sym_injection,
    ACTIONS(53), 1,
      anon_sym_expect,
    STATE(33), 1,
      sym_injection_block,
    STATE(117), 1,
      sym_expect_block,
  [224] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_injection,
    ACTIONS(53), 1,
      anon_sym_expect,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      sym_injection_block,
    STATE(141), 1,
      sym_expect_block,
  [243] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_use,
    ACTIONS(60), 2,
      anon_sym_POUND_LBRACK,
      anon_sym_scenario,
    STATE(14), 2,
      sym_use_declaration,
      aux_sym_source_file_repeat1,
  [258] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_use,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(27), 2,
      sym_use_statement,
      aux_sym_sequence_block_repeat1,
  [272] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    STATE(28), 1,
      aux_sym_annotation_list_repeat1,
    ACTIONS(66), 2,
      anon_sym_RBRACK,
      anon_sym_GT,
  [286] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    ACTIONS(72), 1,
      anon_sym_stream,
    STATE(20), 2,
      sym_stream_statement,
      aux_sym_traffic_block_repeat1,
  [300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 4,
      anon_sym_RBRACK,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [310] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_annotation_list_repeat1,
    ACTIONS(76), 2,
      anon_sym_RBRACK,
      anon_sym_GT,
  [324] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    ACTIONS(80), 1,
      anon_sym_stream,
    STATE(20), 2,
      sym_stream_statement,
      aux_sym_traffic_block_repeat1,
  [338] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 4,
      anon_sym_RBRACK,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [348] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    ACTIONS(87), 1,
      sym_duration,
    STATE(23), 2,
      sym_timeline_segment,
      aux_sym_timeline_expression_repeat1,
  [362] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      sym_duration,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    STATE(24), 2,
      sym_timeline_segment,
      aux_sym_timeline_expression_repeat1,
  [376] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    ACTIONS(93), 1,
      sym_duration,
    STATE(24), 2,
      sym_timeline_segment,
      aux_sym_timeline_expression_repeat1,
  [390] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 4,
      anon_sym_RBRACE,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_miss,
  [400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 4,
      anon_sym_RBRACE,
      anon_sym_hit,
      anon_sym_near_miss,
      anon_sym_miss,
  [410] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_use,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(29), 2,
      sym_use_statement,
      aux_sym_sequence_block_repeat1,
  [424] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_COMMA,
    STATE(28), 1,
      aux_sym_annotation_list_repeat1,
    ACTIONS(102), 2,
      anon_sym_RBRACK,
      anon_sym_GT,
  [438] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_use,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(29), 2,
      sym_use_statement,
      aux_sym_sequence_block_repeat1,
  [452] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(155), 1,
      sym_wave_shape,
    ACTIONS(112), 3,
      anon_sym_sine,
      anon_sym_triangle,
      anon_sym_square,
  [464] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_stream,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_stream_statement,
      aux_sym_traffic_block_repeat1,
  [478] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 3,
      anon_sym_RBRACE,
      anon_sym_injection,
      anon_sym_expect,
  [487] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_expect,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(97), 1,
      sym_expect_block,
  [500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 3,
      anon_sym_RBRACK,
      anon_sym_GT,
      anon_sym_COMMA,
  [509] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 3,
      anon_sym_RBRACE,
      anon_sym_injection,
      anon_sym_expect,
  [518] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_expect,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      sym_expect_block,
  [531] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      sym_identifier,
    STATE(19), 1,
      sym_annotation_item,
    STATE(111), 1,
      sym_annotation_list,
  [544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 3,
      anon_sym_RBRACK,
      anon_sym_GT,
      anon_sym_COMMA,
  [553] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 3,
      anon_sym_RBRACK,
      anon_sym_GT,
      anon_sym_COMMA,
  [562] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(42), 1,
      sym_predicate,
    STATE(125), 1,
      sym_predicate_list,
  [575] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      sym_identifier,
    STATE(19), 1,
      sym_annotation_item,
    STATE(95), 1,
      sym_annotation_list,
  [588] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      aux_sym_predicate_list_repeat1,
  [601] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_predicate_list_repeat1,
  [614] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_predicate_list_repeat1,
  [627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 3,
      anon_sym_use,
      anon_sym_POUND_LBRACK,
      anon_sym_scenario,
  [636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_RBRACE,
      anon_sym_stream,
  [644] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_scenario,
    STATE(157), 1,
      sym_scenario_declaration,
  [654] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_scenario,
    STATE(134), 1,
      sym_scenario_declaration,
  [664] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      anon_sym_RBRACE,
      sym_duration,
  [672] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_use,
    STATE(15), 1,
      sym_use_statement,
  [682] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_RBRACE,
      anon_sym_expect,
  [690] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_traffic,
    STATE(13), 1,
      sym_traffic_block,
  [700] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_traffic,
    STATE(12), 1,
      sym_traffic_block,
  [710] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 2,
      anon_sym_RBRACE,
      anon_sym_stream,
  [718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 2,
      anon_sym_RBRACE,
      anon_sym_stream,
  [726] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 2,
      anon_sym_RBRACE,
      anon_sym_expect,
  [734] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(60), 1,
      sym_predicate,
  [744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      anon_sym_RBRACE,
      anon_sym_stream,
  [752] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [760] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_LT,
    ACTIONS(165), 1,
      anon_sym_LBRACE,
  [778] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
  [788] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 2,
      anon_sym_RBRACE,
      anon_sym_stream,
  [796] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      sym_identifier,
    STATE(39), 1,
      sym_annotation_item,
  [806] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(103), 1,
      sym_sequence_block,
  [816] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 2,
      anon_sym_use,
      anon_sym_RBRACE,
  [824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 2,
      anon_sym_RBRACE,
      anon_sym_stream,
  [832] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 2,
      anon_sym_RBRACE,
      anon_sym_stream,
  [840] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
  [847] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
  [854] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
  [861] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_identifier,
  [868] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LPAREN,
  [875] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_LPAREN,
  [882] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_LBRACE,
  [889] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
  [896] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_GT,
  [903] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
  [910] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
  [917] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_base,
  [924] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_base,
  [931] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_identifier,
  [938] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      sym_identifier,
  [945] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym_comparison_operator,
  [952] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_EQ,
  [959] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_EQ,
  [966] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_EQ,
  [973] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_DOT_DOT,
  [980] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_scenario,
  [987] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_LBRACE,
  [994] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_percent,
  [1001] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym_rate_constant,
  [1008] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym_rate_constant,
  [1015] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_duration,
  [1022] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_RBRACK,
  [1029] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
  [1036] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_RBRACE,
  [1043] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_string,
  [1050] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_COMMA,
  [1057] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_COMMA,
  [1064] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_EQ,
  [1071] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_seq,
  [1078] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
  [1085] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_amp,
  [1092] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_peak,
  [1099] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_rate_constant,
  [1106] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LBRACE,
  [1113] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_gen,
  [1120] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_EQ,
  [1127] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_EQ,
  [1134] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_GT,
  [1141] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_LBRACE,
  [1148] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_rate_constant,
  [1155] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      sym_rate_constant,
  [1162] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_LPAREN,
  [1169] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
  [1176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
  [1183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_COMMA,
  [1190] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_LT,
  [1197] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_RBRACE,
  [1204] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_LT,
  [1211] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_period,
  [1218] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_every,
  [1225] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_EQ,
  [1232] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
  [1239] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
  [1246] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_RBRACE,
  [1253] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_RBRACE,
  [1260] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_EQ,
  [1267] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_EQ,
  [1274] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_LPAREN,
  [1281] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_with,
  [1288] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_LPAREN,
  [1295] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
  [1302] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      sym_duration,
  [1309] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      sym_duration,
  [1316] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      ts_builtin_sym_end,
  [1323] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_LPAREN,
  [1330] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      ts_builtin_sym_end,
  [1337] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      ts_builtin_sym_end,
  [1344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
  [1351] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
  [1358] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      sym_number,
  [1365] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_shape,
  [1372] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_LBRACE,
  [1379] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_hold,
  [1386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_COMMA,
  [1393] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_EQ,
  [1400] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_EQ,
  [1407] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      sym_duration,
  [1414] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_percent,
  [1421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      sym_duration,
  [1428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_LBRACE,
  [1435] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_RPAREN,
  [1442] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_RPAREN,
  [1449] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_RPAREN,
  [1456] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      ts_builtin_sym_end,
  [1463] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      sym_identifier,
  [1470] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_RBRACE,
  [1477] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 73,
  [SMALL_STATE(6)] = 92,
  [SMALL_STATE(7)] = 111,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 149,
  [SMALL_STATE(10)] = 168,
  [SMALL_STATE(11)] = 187,
  [SMALL_STATE(12)] = 205,
  [SMALL_STATE(13)] = 224,
  [SMALL_STATE(14)] = 243,
  [SMALL_STATE(15)] = 258,
  [SMALL_STATE(16)] = 272,
  [SMALL_STATE(17)] = 286,
  [SMALL_STATE(18)] = 300,
  [SMALL_STATE(19)] = 310,
  [SMALL_STATE(20)] = 324,
  [SMALL_STATE(21)] = 338,
  [SMALL_STATE(22)] = 348,
  [SMALL_STATE(23)] = 362,
  [SMALL_STATE(24)] = 376,
  [SMALL_STATE(25)] = 390,
  [SMALL_STATE(26)] = 400,
  [SMALL_STATE(27)] = 410,
  [SMALL_STATE(28)] = 424,
  [SMALL_STATE(29)] = 438,
  [SMALL_STATE(30)] = 452,
  [SMALL_STATE(31)] = 464,
  [SMALL_STATE(32)] = 478,
  [SMALL_STATE(33)] = 487,
  [SMALL_STATE(34)] = 500,
  [SMALL_STATE(35)] = 509,
  [SMALL_STATE(36)] = 518,
  [SMALL_STATE(37)] = 531,
  [SMALL_STATE(38)] = 544,
  [SMALL_STATE(39)] = 553,
  [SMALL_STATE(40)] = 562,
  [SMALL_STATE(41)] = 575,
  [SMALL_STATE(42)] = 588,
  [SMALL_STATE(43)] = 601,
  [SMALL_STATE(44)] = 614,
  [SMALL_STATE(45)] = 627,
  [SMALL_STATE(46)] = 636,
  [SMALL_STATE(47)] = 644,
  [SMALL_STATE(48)] = 654,
  [SMALL_STATE(49)] = 664,
  [SMALL_STATE(50)] = 672,
  [SMALL_STATE(51)] = 682,
  [SMALL_STATE(52)] = 690,
  [SMALL_STATE(53)] = 700,
  [SMALL_STATE(54)] = 710,
  [SMALL_STATE(55)] = 718,
  [SMALL_STATE(56)] = 726,
  [SMALL_STATE(57)] = 734,
  [SMALL_STATE(58)] = 744,
  [SMALL_STATE(59)] = 752,
  [SMALL_STATE(60)] = 760,
  [SMALL_STATE(61)] = 768,
  [SMALL_STATE(62)] = 778,
  [SMALL_STATE(63)] = 788,
  [SMALL_STATE(64)] = 796,
  [SMALL_STATE(65)] = 806,
  [SMALL_STATE(66)] = 816,
  [SMALL_STATE(67)] = 824,
  [SMALL_STATE(68)] = 832,
  [SMALL_STATE(69)] = 840,
  [SMALL_STATE(70)] = 847,
  [SMALL_STATE(71)] = 854,
  [SMALL_STATE(72)] = 861,
  [SMALL_STATE(73)] = 868,
  [SMALL_STATE(74)] = 875,
  [SMALL_STATE(75)] = 882,
  [SMALL_STATE(76)] = 889,
  [SMALL_STATE(77)] = 896,
  [SMALL_STATE(78)] = 903,
  [SMALL_STATE(79)] = 910,
  [SMALL_STATE(80)] = 917,
  [SMALL_STATE(81)] = 924,
  [SMALL_STATE(82)] = 931,
  [SMALL_STATE(83)] = 938,
  [SMALL_STATE(84)] = 945,
  [SMALL_STATE(85)] = 952,
  [SMALL_STATE(86)] = 959,
  [SMALL_STATE(87)] = 966,
  [SMALL_STATE(88)] = 973,
  [SMALL_STATE(89)] = 980,
  [SMALL_STATE(90)] = 987,
  [SMALL_STATE(91)] = 994,
  [SMALL_STATE(92)] = 1001,
  [SMALL_STATE(93)] = 1008,
  [SMALL_STATE(94)] = 1015,
  [SMALL_STATE(95)] = 1022,
  [SMALL_STATE(96)] = 1029,
  [SMALL_STATE(97)] = 1036,
  [SMALL_STATE(98)] = 1043,
  [SMALL_STATE(99)] = 1050,
  [SMALL_STATE(100)] = 1057,
  [SMALL_STATE(101)] = 1064,
  [SMALL_STATE(102)] = 1071,
  [SMALL_STATE(103)] = 1078,
  [SMALL_STATE(104)] = 1085,
  [SMALL_STATE(105)] = 1092,
  [SMALL_STATE(106)] = 1099,
  [SMALL_STATE(107)] = 1106,
  [SMALL_STATE(108)] = 1113,
  [SMALL_STATE(109)] = 1120,
  [SMALL_STATE(110)] = 1127,
  [SMALL_STATE(111)] = 1134,
  [SMALL_STATE(112)] = 1141,
  [SMALL_STATE(113)] = 1148,
  [SMALL_STATE(114)] = 1155,
  [SMALL_STATE(115)] = 1162,
  [SMALL_STATE(116)] = 1169,
  [SMALL_STATE(117)] = 1176,
  [SMALL_STATE(118)] = 1183,
  [SMALL_STATE(119)] = 1190,
  [SMALL_STATE(120)] = 1197,
  [SMALL_STATE(121)] = 1204,
  [SMALL_STATE(122)] = 1211,
  [SMALL_STATE(123)] = 1218,
  [SMALL_STATE(124)] = 1225,
  [SMALL_STATE(125)] = 1232,
  [SMALL_STATE(126)] = 1239,
  [SMALL_STATE(127)] = 1246,
  [SMALL_STATE(128)] = 1253,
  [SMALL_STATE(129)] = 1260,
  [SMALL_STATE(130)] = 1267,
  [SMALL_STATE(131)] = 1274,
  [SMALL_STATE(132)] = 1281,
  [SMALL_STATE(133)] = 1288,
  [SMALL_STATE(134)] = 1295,
  [SMALL_STATE(135)] = 1302,
  [SMALL_STATE(136)] = 1309,
  [SMALL_STATE(137)] = 1316,
  [SMALL_STATE(138)] = 1323,
  [SMALL_STATE(139)] = 1330,
  [SMALL_STATE(140)] = 1337,
  [SMALL_STATE(141)] = 1344,
  [SMALL_STATE(142)] = 1351,
  [SMALL_STATE(143)] = 1358,
  [SMALL_STATE(144)] = 1365,
  [SMALL_STATE(145)] = 1372,
  [SMALL_STATE(146)] = 1379,
  [SMALL_STATE(147)] = 1386,
  [SMALL_STATE(148)] = 1393,
  [SMALL_STATE(149)] = 1400,
  [SMALL_STATE(150)] = 1407,
  [SMALL_STATE(151)] = 1414,
  [SMALL_STATE(152)] = 1421,
  [SMALL_STATE(153)] = 1428,
  [SMALL_STATE(154)] = 1435,
  [SMALL_STATE(155)] = 1442,
  [SMALL_STATE(156)] = 1449,
  [SMALL_STATE(157)] = 1456,
  [SMALL_STATE(158)] = 1463,
  [SMALL_STATE(159)] = 1470,
  [SMALL_STATE(160)] = 1477,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_injection_block_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_injection_block_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expect_block_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expect_block_repeat1, 2, 0, 0), SHIFT_REPEAT(131),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation_list, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation_list, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_traffic_block_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_traffic_block_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_timeline_expression_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_timeline_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expect_statement, 6, 0, 6),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_injection_case, 8, 0, 7),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_annotation_list_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_annotation_list_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_block_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_block_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_traffic_block, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_traffic_block, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation_item, 3, 0, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_list, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_list, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_predicate_list_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_predicate_list_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_declaration, 2, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wave_expression, 14, 0, 10),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timeline_segment, 5, 0, 8),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_injection_block, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rate_expression, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stream_statement, 4, 0, 5),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_injection_block, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timeline_expression, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 3, 0, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timeline_expression, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_statement, 10, 0, 11),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wave_expression, 18, 0, 12),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_burst_expression, 18, 0, 13),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 9, 0, 4),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [195] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 10, 0, 4),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_attributes, 3, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 6, 0, 3),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode_keyword, 1, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_block, 5, 0, 9),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_block, 6, 0, 9),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expect_block, 3, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expect_function, 1, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 7, 0, 3),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 8, 0, 4),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_declaration, 5, 0, 3),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wave_shape, 1, 0, 0),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expect_block, 4, 0, 0),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wfg(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "wfg",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
